#!/bin/bash

# Make sure that NOBODY can access the server without a password.
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '12erthjkiuygfds';"

# Create new user.
mysql -e "CREATE USER 'userDB'@'%' IDENTIFIED BY 'password';"

# Grant privileges for new user.
mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'userDB'@'%';"

# Make our changes take effect.
mysql -e "FLUSH PRIVILEGES;"



# Create database for web.
mysql -u userDB -ppassword -e "CREATE DATABASE myDB;"

# Create table for web.
mysql -u userDB -ppassword -e "USE myDB; CREATE TABLE ScoreBoard (ID int NOT NULL AUTO_INCREMENT PRIMARY KEY, Name text, Score int);"



# Edit mysqld settings.
sed -i 's/^bind-address/#bind-address/g' /etc/mysql/mysql.conf.d/mysqld.cnf

# Restart mysqld.
service mysql restart
